export default [
  { value: 'a', label: 'A - Agriculture, Forestry And Fishing' },
  { value: 'b', label: 'B - Mining And Quarrying' },
  { value: 'c', label: 'C - Manufacturing' },
  { value: 'd', label: 'D - Electricity, Gas, Steam And Air-Conditioning Supply' },
  { value: 'e', label: 'E - Water Supply; Sewerage, Waste Management And Remediation Activities' },
  { value: 'f', label: 'F - Construction' },
  { value: 'g', label: 'G - Wholesale And Retail Trade; Repair Of Motor Vehicles And Motorcycles' },
  { value: 'h', label: 'H - Transportation And Storage' },
  { value: 'i', label: 'I - Accommodation And Food Service Activities' },
  { value: 'j', label: 'J - Information And Communication' },
  { value: 'k', label: 'K - Financial And Insurance Activities' },
  { value: 'l', label: 'L - Real Estate Activities' },
  { value: 'm', label: 'M - Professional, Scientific And Technical Activities' },
  { value: 'n', label: 'N - Administrative And Support Service Activities' },
  { value: 'o', label: 'O - Public Administration And Defence; Compulsory Social Security' },
  { value: 'p', label: 'P - Education' },
  { value: 'q', label: 'Q - Human Health And Social Work Activities' },
  { value: 'r', label: 'R - Arts, Entertainment And Recreation' },
  { value: 's', label: 'S - Other Service Activities' },
  { value: 't', label: 'T - Activities Of Households As Employers; Undifferentiated Goods- And Services-Producing Activities Of Households For Own Use' },
  { value: 'u', label: 'U - Activities Of Extraterritorial Organisations And Bodies' },
]
