name: Quasar build and deploy

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Build"
        shell: bash
        run: |
          npm run build
      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: dist/spa
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
